on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          for run in {1..60}; do
            echo "Log line: $run"
            sleep 1m
          done
